import { Container, Flex, Spacer } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import Project from "./project";
import {
  Heading,
  Avatar,
  Box,
  Center,
  Text,
  Stack,
  Button,
  Link,
  Badge,
  useColorModeValue,
} from "@chakra-ui/react";
import Project from "./project";
import Experience from "./experience";

export default function Home({ profile }) {
  console.log(profile);
  return (
    <div className={styles.container}>
      <Head>
        <title>Mukesh Kaushal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div maxW="full" style={{ width: "100%" }}>
        <Flex>
          <Box width="25%">
            <Center py={6}>
              <Box
                maxW={"390px"}
                w={"full"}
                bg={useColorModeValue("white", "gray.900")}
                boxShadow={"xl"}
                border = "2px solid black"
                rounded={"lg"}
                p={6}
                textAlign={"center"}
              >
                <Avatar
                  size={"xl"}
                  src={profile.avatar_url}
                  alt={"Avatar Alt"}
                  mb={4}
                  height = "150px"
                  width = "150px"

                  pos={"relative"}
                  _after={{
                    content: '""',
                    w: 2,
                    h: 2,
                    bg: "green.300",
                    border: "2px solid white",
                    rounded: "full",
                    pos: "absolute",
                    bottom: 0,
                    right: 3,
                  }}
                />
                <Heading fontSize={"2xl"} fontFamily={"body"}>
                  {profile.name}
                </Heading>
                <Text fontWeight={600} color={"gray.500"} mb={4}>
                  @{profile.login}
                </Text>
                <Text
                  textAlign={"center"}
                  color={useColorModeValue("gray.700", "gray.400")}
                  px={3}
                >
                  {profile.bio}{" "}
                </Text>

                <Stack mt={8} direction={"row"} spacing={4}>
                  <Button
                    flex={1}
                    fontSize={"sm"}
                    rounded={"full"}
                    _focus={{
                      bg: "gray.200",
                    }}
                  >
                    Resume
                  </Button>
                  <Button
                    flex={1}
                    fontSize={"sm"}
                    rounded={"full"}
                    bg={"blue.400"}
                    color={"white"}
                    p={2}
                    boxShadow={
                      "0px 1px 25px -5px rgb(66 153 225 / 48%), 0 10px 10px -5px rgb(66 153 225 / 43%)"
                    }
                    _hover={{
                      bg: "blue.500",
                    }}
                    _focus={{
                      bg: "blue.500",
                    }}
                  >
                    <Link>Follow</Link>
                  </Button>
                </Stack>
              </Box>
            </Center>
            <Flex ml = {4} mt = {8}>
            
              <p
                style={{
                
                  backgroundColor: "green",
                  color: "white",
                  borderRadius : "10px",
                  padding : "5px",
                  fontSize : "12px",
                  marginLeft : "20px"
                }}
              >
                HTML
              </p>
              <p
                style={{
              
                  backgroundColor: "orange",
                  color: "white",
                  borderRadius : "10px",
                  padding : "5px",
                  fontSize : "12px",
                  marginLeft : "20px"
                }}
              >
                Javascript
              </p>
              <p
                style={{
                
                  backgroundColor: "teal",
                  color: "white",
                  borderRadius : "10px",
                  padding : "5px",
                  paddingLeft : "10px",
                  paddingRight : "10px",
                  fontSize : "12px",
                  marginLeft : "20px"
                }}
              >
                React
              </p>
              <p
                style={{
         
                  backgroundColor: "blue",
                  color: "white",
                  borderRadius : "10px",
                  padding : "5px",
                  paddingLeft : "10px",
                  paddingRight : "10px",
                  fontSize : "12px",
                  marginLeft : "20px"
                }}
              >
                Mongo DB
              </p>
            </Flex>

            <Experience/>
          </Box>

          <Spacer />
          <Box width="50%">
                
          </Box>
        </Flex>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  let response = await fetch(`https://api.github.com/users/imukeshkaushal`);
  let data = await response.json();

  return {
    props: {
      profile: data,
    },
  };
}

